Migrate from Dockerhub to Amazon ECR.

diff --git a/bin/build-docker b/bin/build-docker
--- a/bin/build-docker
+++ b/bin/build-docker
@@ -1,7 +1,7 @@
 #!/bin/bash
 set -e
 
-export REPO=chanzuckerberg/idseq-web
+export REPO="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/idseq-web"
 
 BRANCH="$1"
 BRANCH_CLEANED=`echo $BRANCH | sed 's/\//-/g'`
@@ -20,8 +20,8 @@ echo '--'
 
 # Try to pull the latest image for this branch, otherwise pull latest image for caching
 if ! ( docker pull $BRANCH_TAG && docker tag $BRANCH_TAG $CACHE_TAG ); then
-  docker pull $LATEST_TAG
-  docker tag $LATEST_TAG $CACHE_TAG
+  # If we fail to fetch the latest image, continue the build without a cache image.
+  (docker pull $LATEST_TAG && docker tag $LATEST_TAG $CACHE_TAG) || true
 fi
 
 docker build -t $COMPOSE_TAG --cache-from $CACHE_TAG --build-arg GIT_COMMIT=${COMMIT} .
